<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
  <TargetFramework>net10.0</TargetFramework>
  <Nullable>enable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>
  
  <!-- Add these two lines to bypass SRI/ICU dat proxy blocks -->
  <InvariantGlobalization>true</InvariantGlobalization>
  <BlazorCacheBootResources>false</BlazorCacheBootResources>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIPersonalFinanceTracker.Shared\AIPersonalFinanceTracker.Shared.csproj" />
  </ItemGroup>

</Project>
